### ISSUE TITLE
Problem importing data from SMT report.csv

### ISSUE THREAD

**Issue by memilanuk** [dwoll/shotGroups#1]
Finally got a chance to import some data from a load development session on the club's SMT G2 e-targets.  Saved the CSV file to a location accessible to RStudio, got the `shotGroups` package installed, and tried importing the data file.
```

> DFgroups <- readDataSMT(fNames = "2019-01-05_Sav-FTR-1_report_SMT.csv")
Error in FUN(X[[i]], ...) : could not find function "hasName"
```

Not sure if I'm not doing this right, or if I'm still missing a library file somewhere (had some issues getting `CompQuadForm` to compile and install), or something else...

FWIW, I am able to read the CSV file into RStudio using the gui tools (click on file name, then 'Import dataset'), and then rename the resulting DF as `DFgroups`.

**Comment by dwoll** [comment]
Monte, good to hear from you again! Function `hasName()` is part of base R since version 3.4. This error should go away once you upgrade to a recent version of R - current version is 3.5.2. Be advised that you will have to re-install shotGroups (and other packages you're using) after a major version upgrade. Does that solve your problem?

**Comment by memilanuk** [comment]
Ah.  Running Linux via [crouton](https://github.com/dnschneid/crouton/) on my Dell CB13... I think I had the default (3.2.3) version of R installed from the distro repos (xenial).  Whoops!

Got a new entry in the package source list pointing at the CRAN repos instead.  Now to get everything (re)installed and compiled... on an i3 ;)
